backend:
  name: turbo-github
  turbo_site_id: a5d18cb4-c968-4432-b0ab-5f917339519c
  branch: main
media_folder: "assets/uploads"
media_library:
  name: default
collections:
  - name: catalogo
    label: Catálogo
    files:
      - name: productos
        label: Productos
        file: data/products.json
        fields:
          - label: Productos
            name: products
            widget: list
            fields:
              - { label: ID, name: id, widget: string }
              - { label: Nombre, name: name, widget: string }
              - { label: Categoría, name: category, widget: string }
              - { label: Precio, name: price, widget: number }
              - { label: Descripción, name: desc, widget: text }
              - { label: Imagen, name: image, widget: image, required: false }
